config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get '/search'  =>'homes#search', :as=>'search'
  get ':username/:note_id'  =>"notes#show", :as=>"note"
  get ':username'  =>"notes#user", :as=>"user"
  resources :notes, except: [:show]
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :time_at, :body, :username, :note_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @note = Note.new
  end

  def search
    @query = params[:note_search][:query]
    if !@query.blank?
      redirect_to user_path(@query)
    else
      redirect_to root_path
      #TODO flash message
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
  end

  def create
    @note = Note.new note_params
    if @note.save
      @username = @note.username
      @note_id = @note.note_id
      redirect_to note_path(@username,@note_id)
    else
      render template: "homes/index"
    end
  end

  def show
    @note = Note.find_by_note_id(params[:note_id])
  end

  def user
    @notes =Note.where("username = ?", params[:username])
  end

  private
    
    def note_params
      params.require(:note).permit(:time_at,
                                   :body,
                                   :username,
                                   :note_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/homes/_form.html.erb
<div class="describe">
  <h1>Shorthand —— 记一切所看所感所闻之事</h1>
</div>
<%=form_for @note, url: notes_path, html: { class: "ui form"} do |f| %>
  <div class="field">
    <div class="ui icon input">
      <%=f.text_field :time_at,:placeholder=>"挑一个记事时间",:id=>"datetimepicker"%>
      <i class="calendar icon"></i>
    </div>
  </div>
  <div class="field">
    <label>这里填写内容</label>
    <%=f.text_area :body, :placeholder=>"你可以在这里详细的描述......"%>
  </div>
  <div class="two fields">
    <div class="field">
      <div class="ui labeled input">
        <div class="ui label">http://localhost:3000/</div>
        <%=f.text_field :username, :placeholder=>"英文名如 user1"%>
      </div>
    </div>
    <div class="field">
      <%= f.text_field :note_id,:placeholder=>"填一个查看地址ID，如 1"%>
    </div>
  </div>
  <div class="field">
    <%=f.submit "保 存",class: "fluid ui button green"%>
  </div>
<%end%>  

app/views/homes/_slider.html.erb
<div class="ui positive message">
  <div class="header">
    为什么选择Shorthand?
  </div>
  <ul class="list">
    <li>操作简单、界面简洁.</li>
    <li>无须注册与登录，为你去除繁琐的功能.</li>
    <li>专重内容书写与展示的便易.</li>
  </ul>
</div>
<div class="ui positive message">
  <div class="header">
    操作说明：
  </div>
  <ul class="list">
    <li>选择一个本次记事的时间点.</li>
    <li>查看地址最好填写一个你喜欢且易记的英文名字加数字如: user1/1.</li>
    <li>本次的记录你将会在 http://localhost:3000/user1/1 地址看到.</li>
    <li>每次的记事的英文名字最好相同，这样你的所有记事将会在类似 http://localhost:3000/user1 这样的地址查看.</li>
  </ul>
</div>

app/views/homes/index.html.erb
<div class="home">
  <div class="ui grid">
    <div class="nine wide column">
      <%=render 'homes/form'%>
    </div>
    <div class="six wide  column">
      <%=render 'homes/slider'%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shorthand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%="#{controller_name}-#{action_name == "index" ? "page" : action_name}"%>">
  
  <%= render 'shared/header'%>
  <%= yield %>

</body>
</html>

app/views/notes/show.html.erb
<p><%=@note.time_at%></p>
<p><%=@note.body%></p>
<p><a href="<%=@note.note_id%>">http:localhost:3000/<%=@note.username %>/<%=@note.note_id%></a></p>

app/views/notes/user.html.erb
<%@notes.each do |note|%>
  <p><a href="<%=note_path(note.username,note.note_id)%>"><%=note.time_at%></a></p>
  <p><%=truncate note.body%></p>
<%end%>

app/views/shared/_header.html.erb
<div class="ui menu">
  <div class="container">
    <div class="item">
      <%=form_for :note_search, url: search_path,method: :get do |f|%>
        <div class="ui icon input">
          <%= f.text_field :query, placeholder: "搜索用户名，如 user1"%>
          <i class="search icon"></i>
        </div>
      <%end%>
    </div>
    <div class="right item">
      <a href="/">
        <i class="write square icon"></i>
      </a>
    </div>
  </div>
</div>